Repository cozy/cozy-libs, pull requests merged in 2018-08, with the labels that each got.

#21 Realtime: Add `domain` and `secure` to config
  packages/realtime/src/index.js
Labels: bug, enhancement

#22 Add watch task for realtime
  packages/realtime/package.json
Labels: enhancement

#24 Fix some bugs
  packages/interapp/src/intents.js
  packages/interapp/src/intents.spec.js
  packages/interapp/src/request.js
  packages/interapp/src/request.spec.js
Labels: interapp

#29 Explicit usage of encrypted private key
  packages/cozy-app-publish/README.md
Labels: enhancement

#31 Better options check
  packages/cozy-app-publish/lib/prepublish.js
  packages/cozy-app-publish/test/__mocks__/prepublish-bad-value-options-hook.js
  packages/cozy-app-publish/test/__mocks__/prepublish-missing-manifest-options-hook.js
  packages/cozy-app-publish/test/__mocks__/prepublish-missing-options-hook.js
  packages/cozy-app-publish/test/__snapshots__/prepublish.spec.js.snap
  packages/cozy-app-publish/test/prepublish.spec.js
Labels: enhancement
