Repository cozy/cozy-libs, pull requests merged in 2018-09, with the labels that each got.

#39 Avoid `undefined` in archive folder
  packages/cozy-app-publish/lib/hooks/pre/downcloud.js
Labels: bug

#40 [WIP] Add new cozy-release tool
  CODEOWNERS
  packages/cozy-release/README.md
  packages/cozy-release/cozy-release.js
  packages/cozy-release/package.json
  packages/cozy-release/scripts/cozy-release.sh
  yarn.lock
Labels: cozy-release

#46 Enhancements for cozy-release
  packages/cozy-release/scripts/cozy-release.sh
Labels: enhancement

#49 Add limitation on body 📏
  package.json
  packages/commitlint-config/README.md
  packages/commitlint-config/index.js
  packages/commitlint-config/index.spec.js
  packages/commitlint-config/package.json
  yarn.lock
Labels: commitlint

#50 Make Travis fail on publish, prepublish or postpublish error
  packages/cozy-app-publish/cozy-app-publish.js
  packages/cozy-app-publish/lib/publish.js
  packages/cozy-app-publish/lib/travis.js
  packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
  packages/cozy-app-publish/test/travis.spec.js
Labels: enhancement

#54 Make shift command works on every shell
  packages/cozy-release/scripts/cozy-release.sh
Labels: bug

#55 cozy-release: Detect cozy remote
  packages/cozy-release/scripts/cozy-release.sh
Labels: enhancement

#59 Fix shebang (again)
  packages/cozy-release/scripts/cozy-release.sh
Labels: bug

#60 Make cozy-release work with konnectors as well
  packages/cozy-release/scripts/cozy-release.sh
Labels: enhancement

#61 Change semver parsing
  packages/cozy-release/scripts/cozy-release.sh
Labels: enhancement

#63 Add pull-request option for cozy-release start
  packages/cozy-release/scripts/cozy-release.sh
Labels: enhancement
