Repository cozy/cozy-libs, pull requests merged in 2019-07, with the labels that each got.

#560 Harvest: Fix undefined proptypes when transpiled
  packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
Labels: bug

#567 Harvest: Better synchronisation between components in KonnectorModal
  packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
  packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
  packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/src/components/cards/DeleteAccountCard.jsx
  packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
Labels: ✨ Enhancement

#588 Harvest: When refetching, trigger must be retrieved from state
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
Labels: bug

#602 Harvest: Check after tx pull ☑
  packages/cozy-harvest-lib/package.json
  packages/cozy-harvest-lib/scripts/check-locales.sh
Labels: ✨ Enhancement

#650 Change name of package PackageInfoPlugin
  packages/webpack-expose-package-info-plugin/package.json
  packages/webpack-expose-package-info-plugin/src/index.js
Labels: merge

#597 Add connectWithProcedures HOC
  packages/cozy-procedures/src/containers/Amount.jsx
  packages/cozy-procedures/src/containers/CompletedFromDriveStatus.jsx
  packages/cozy-procedures/src/containers/CompletedFromMyselfStatus.jsx
  packages/cozy-procedures/src/containers/DocumentsDataForm.jsx
  packages/cozy-procedures/src/containers/Duration.jsx
  packages/cozy-procedures/src/containers/Overview.jsx
  packages/cozy-procedures/src/containers/PersonalDataForm.jsx
  packages/cozy-procedures/src/containers/Procedure.jsx
  packages/cozy-procedures/src/redux/connectWithProcedures.js
  packages/cozy-procedures/src/redux/connectWithProcedures.spec.js
Labels: merge

#662 feat: Add two small utilities
  packages/cozy-codeshifts/src/transforms/remove-unused-imports.js
  packages/cozy-codeshifts/src/utils/add-import.js
Labels: merge

#671 Cozy logger in cozy-libs
  README.md
  packages/cozy-logger/README.md
  packages/cozy-logger/package.json
  packages/cozy-logger/src/Secret.js
  packages/cozy-logger/src/dev-format.js
  packages/cozy-logger/src/index.js
  packages/cozy-logger/src/log-filters.js
  packages/cozy-logger/src/log-format.js
  packages/cozy-logger/src/log-formats.spec.js
  packages/cozy-logger/src/prod-format.js
Labels: merge

#674 chore: Update deprecated config
  lerna.json
Labels: merge

#669 feat: Lib option to babel-preset-cozy-app
  .travis.yml
  packages/babel-preset-cozy-app/README.md
  packages/babel-preset-cozy-app/index.js
  packages/cozy-authentication/babel.config.js
  packages/cozy-procedures/babel.config.js
Labels: merge

#677 feat(cozy-procedures): Use input group to display €/mois
  packages/cozy-procedures/src/components/form/InputWithUnit.jsx
  packages/cozy-procedures/src/components/form/__snapshots__/InputWithUnit.spec.jsx.snap
  packages/cozy-procedures/src/locales/en.json
  packages/cozy-procedures/src/locales/fr.json
Labels: merge

#681 Doctypes: Add Folder class
  packages/cozy-doctypes/src/Application.js
  packages/cozy-doctypes/src/Folder.js
  packages/cozy-doctypes/src/Folder.spec.js
  packages/cozy-doctypes/src/index.js
Labels: ✨ Enhancement
