Repository cozy/cozy-libs, pull requests merged in 2019-03, with the labels that each got.

#297 Harvest: Force folder_to_save for trigger
  packages/cozy-harvest-lib/src/Manifest.js
  packages/cozy-harvest-lib/src/Manifest.spec.js
  packages/cozy-harvest-lib/src/components/AccountCreator.jsx
  packages/cozy-harvest-lib/src/components/AccountEditor.jsx
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/src/connections/files.js
  packages/cozy-harvest-lib/src/connections/permissions.js
  packages/cozy-harvest-lib/src/helpers/accounts.js
  packages/cozy-harvest-lib/src/helpers/cron.js
  packages/cozy-harvest-lib/src/helpers/konnectors.js
  packages/cozy-harvest-lib/src/helpers/slug.js
  packages/cozy-harvest-lib/src/helpers/triggers.js
  packages/cozy-harvest-lib/src/locales/en.json
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
  packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
  packages/cozy-harvest-lib/test/connections/files.spec.js
  packages/cozy-harvest-lib/test/connections/permission.spec.js
  packages/cozy-harvest-lib/test/helpers/accounts.spec.js
  packages/cozy-harvest-lib/test/helpers/cron.spec.js
  packages/cozy-harvest-lib/test/helpers/konnectors.spec.js
  packages/cozy-harvest-lib/test/helpers/slug.spec.js
  packages/cozy-harvest-lib/test/helpers/triggers.spec.js
Labels: enhancement

#307 Harvest: allow float in randomDayTime() helper
  packages/cozy-harvest-lib/src/helpers/daytime.js
  packages/cozy-harvest-lib/test/helpers/daytime.spec.js
Labels: bug

#305 Harvest: Handle Errors during account, files and trigger mutations
  packages/cozy-harvest-lib/jest.config.js
  packages/cozy-harvest-lib/package.json
  packages/cozy-harvest-lib/src/assets/images/connecting.svg
  packages/cozy-harvest-lib/src/components/AccountCreator.jsx
  packages/cozy-harvest-lib/src/components/AccountEditor.jsx
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
  packages/cozy-harvest-lib/src/components/AccountFormError.jsx
  packages/cozy-harvest-lib/src/components/Markdown.jsx
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/src/components/TriggerSuccessMessage.jsx
  packages/cozy-harvest-lib/src/connections/accounts.js
  packages/cozy-harvest-lib/src/connections/triggers.js
  packages/cozy-harvest-lib/src/helpers/konnectors.js
  packages/cozy-harvest-lib/src/locales/en.json
  packages/cozy-harvest-lib/test/__mocks__/file.js
  packages/cozy-harvest-lib/test/components/AccountCreator.spec.js
  packages/cozy-harvest-lib/test/components/AccountEditor.spec.js
  packages/cozy-harvest-lib/test/components/AccountForm.spec.js
  packages/cozy-harvest-lib/test/components/AccountFormError.spec.js
  packages/cozy-harvest-lib/test/components/OAuthForm.spec.js
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
  packages/cozy-harvest-lib/test/components/TriggerSuccessMessage.spec.js
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountCreator.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountEditor.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountFormError.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/TriggerSuccessMessage.spec.js.snap
  packages/cozy-harvest-lib/test/connections/accounts.spec.js
  packages/cozy-harvest-lib/test/helpers/konnectors.spec.js
  packages/cozy-harvest-lib/test/setup.js
  yarn.lock
Labels: enhancement

#311 Harvest: Ensure trigger can be launched, even after creation error
  packages/cozy-harvest-lib/src/components/AccountFormError.jsx
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
Labels: enhancement

#315 Harvest: Prevent undefined Error.captureStackTrace()
  packages/cozy-harvest-lib/src/helpers/konnectors.js
Labels: bug

#320 Harvest: avoid warnings in tests
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
  packages/cozy-harvest-lib/test/connections/accounts.spec.js
Labels: enhancement

#318 Harvest: Handle onKeyUp on whole AccountFields component
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
Labels: enhancement

#316 Harvest: Give focus to identifier field
  packages/cozy-harvest-lib/package.json
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
  yarn.lock
Labels: enhancement

#317 Harvest: Show error when editing
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/src/helpers/triggers.js
  packages/cozy-harvest-lib/test/components/AccountForm.spec.js
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
  packages/cozy-harvest-lib/test/helpers/triggers.spec.js
Labels: Harvest, enhancement

#312 Harvest (refactoring): Découpage nécessaire de notre beau formulaire
  packages/cozy-harvest-lib/src/components/AccountForm.jsx
  packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
  packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx
  packages/cozy-harvest-lib/src/components/AccountForm/Error.jsx
  packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
  packages/cozy-harvest-lib/test/components/AccountField.spec.js
  packages/cozy-harvest-lib/test/components/AccountFields.spec.js
  packages/cozy-harvest-lib/test/components/AccountForm.spec.js
  packages/cozy-harvest-lib/test/components/AccountFormError.spec.js
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountFields.spec.js.snap
  packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Labels: Harvest, enhancement

#314 Harvest: cleaning
  packages/cozy-harvest-lib/src/Harvest.jsx
  packages/cozy-harvest-lib/src/Harvest.spec.jsx
  packages/cozy-harvest-lib/src/__snapshots__/Harvest.spec.jsx.snap
  packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
  packages/cozy-harvest-lib/src/helpers/accounts.js
  packages/cozy-harvest-lib/src/helpers/manifest.js
  packages/cozy-harvest-lib/test/helpers/manifest.spec.js
Labels: Harvest, enhancement

#326 refactor: Extract common code between manual/travis as publisher
  packages/cozy-app-publish/lib/manual.js
  packages/cozy-app-publish/lib/publisher.js
  packages/cozy-app-publish/lib/travis.js
  packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
  packages/cozy-app-publish/test/manual.spec.js
  packages/cozy-app-publish/test/travis.spec.js
Labels: publish

#327 feat: Support tag prefix
  packages/cozy-app-publish/cozy-app-publish.js
  packages/cozy-app-publish/lib/manual.js
  packages/cozy-app-publish/lib/tags.js
  packages/cozy-app-publish/lib/tags.spec.js
  packages/cozy-app-publish/lib/travis.js
  packages/cozy-app-publish/package.json
  packages/cozy-app-publish/test/__snapshots__/manual.spec.js.snap
  packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
  packages/cozy-app-publish/test/manual.spec.js
  packages/cozy-app-publish/test/travis.spec.js
Labels: publish

#330 Harvest: Use existing trigger and avoir trigger duplication
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
  packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
  packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
Labels: bug

#332 Harvest: Success callbacks may be undefined
  packages/cozy-harvest-lib/src/components/TriggerManager.jsx
Labels: bug

#334 Harvest: Login Failed message was wrong
  packages/cozy-harvest-lib/src/locales/en.json
Labels: enhancement

#328 Harvest: Split concern between AccountField and manifest
  packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
  packages/cozy-harvest-lib/src/helpers/manifest.js
Labels: enhancement

#339 Configure styleguidist
  .gitignore
  babel.config.js
  docs/styleguidist.config.js
  package.json
  packages/cozy-harvest-lib/package.json
  yarn.lock
Labels: enhancement

#346 Harvest: detect user errors
  packages/cozy-harvest-lib/src/helpers/konnectors.js
  packages/cozy-harvest-lib/src/index.js
  packages/cozy-harvest-lib/test/helpers/konnectors.spec.js
  packages/cozy-harvest-lib/test/index.spec.js
Labels: ✨ Enhancement

#362 Initialize realtime with uri from CozyClient
  packages/cozy-harvest-lib/src/connections/triggers.js
Labels: bug
